[versions]
ksp = "2.1.0-1.0.29"

[libraries]
symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }